teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 3 # 0 for left stick, 3 for right stick
    scale_angular:
      yaw: 0.4
    scale_angular_turbo:
      yaw: 0.6

    enable_button: 6 # Left Trigger
    enable_turbo_button: 7 # Right Trigger

# setup guide here:
# https://docs.nvidia.com/isaac/packages/sensors/doc/joystick.html?highlight=joystick
