teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 0
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 1
    scale_angular:
      yaw: 1.0
    scale_angular:
      yaw: 1.5

    enable_button: 6  # Left Trigger
    enable_turbo_button: 7  # Right Trigger
